# Templated by `cargo-generate` using https://github.com/danielhenrymantilla/proc-macro-template
name: Cron CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1,5'

jobs:
  # == TEST == #
  test-no-ui:
    name: (Check & Build &) Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # What we want to test: (stable, cargo update), (beta, --locked), (nightly, cargo update).
        future-proof:
          # Future-proof against non-locked regressions.
          - rust-toolchain: stable
            cargo-locked: '' # --locked already tested in CI, and in future-proof of beta.
          # Future-proof against compiler-regressions
          - rust-toolchain: beta # "nigh stable"
            cargo-locked: '--locked'
          - rust-toolchain: nightly
            cargo-locked: ''
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          override: true
          toolchain: ${{ matrix.future-proof.rust-toolchain }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update `Cargo.lock`
        if: matrix.future-proof.cargo-locked != '--locked'
        run: cargo update -v

      - name: Cargo test
        uses: actions-rs/cargo@v1
        env:
          RUSTC_BOOTSTRAP: 1
        with:
          command: test
          args: ${{ matrix.future-proof.cargo-locked }} --features better-docs

      - name: Cargo test (embed `README.md` + UI)
        if: matrix.future-proof.rust-toolchain == 'beta'
        uses: actions-rs/cargo@v1
        env:
          RUSTC_BOOTSTRAP: 1
        with:
          command: test-ui
