# Templated by `cargo-generate` using https://github.com/danielhenrymantilla/proc-macro-template
name: Cron CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1,5'

jobs:
  # == TEST == #
  test-no-ui:
    name: (Check & Build &) Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # What we want to test: (stable, cargo update), (beta, --locked), (nightly, cargo update).
        rust-toolchain:
          # Future-proof against non-locked regressions.
          - stable
          # Future-proof against compiler-regressions
          - nightly
        cargo-locked: ['']
        include:
          # Let's check for a compiler regression of `--locked`.
          - rust-toolchain: beta
            cargo-locked: '--locked'
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          override: true
          toolchain: ${{ matrix.rust-toolchains }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update `Cargo.lock`
        if: matrix.cargo-locked != '--locked'
        run: cargo update -v

      - name: Cargo test
        uses: actions-rs/cargo@v1
        env:
          RUSTC_BOOTSTRAP: 1
        with:
          command: test
          args: ${{ matrix.cargo-locked }} --features better-docs

      - name: Cargo test (embed `README.md` + UI)
        if: matrix.rust-toolchains == 'beta'
        uses: actions-rs/cargo@v1
        env:
          RUSTC_BOOTSTRAP: 1
        with:
          command: test-ui
